Repository FromDoppler/doppler-style-guide, pull requests merged in 2022-11, with the labels that each got.

#176 fix: add classes to segments button
  src/assets/scss/modules/_buttons.scss
Labels: size/XS

#179 Feat grid update for old doppler
  src/assets/scss/helpers/_classes.scss
  src/assets/scss/modules/_buttons.scss
Labels: size/L

#180 fix: fix in create templates button
  src/assets/scss/helpers/_classes.scss
Labels: size/S

#182 fix: alignment of create campaign and link colors
  src/assets/scss/helpers/_classes.scss
Labels: size/M

#185 fix: color links in cancel and delete
  src/assets/scss/helpers/_classes.scss
Labels: size/XS

#186 fix: incorrect focus display in Jquery selectBox plugin classes
  src/assets/scss/helpers/_classes.scss
Labels: size/S

#187 feat: add quick actions
  src/assets/scss/templates/_dashboard.scss
  src/documentation/templates/dashboard.html
Labels: size/M

#193 fix: align icons in table
  src/assets/scss/helpers/_classes.scss
Labels: size/XS

#195 build: fix gitlint
  gitlint.sh
Labels: size/XS
