Repository FromDoppler/doppler-style-guide, pull requests merged in 2022-10, with the labels that each got.

#158 feat: add hero banner text center for doppler
  src/assets/scss/templates/_reportes.scss
Labels: size/XS

#159 feat: add a zero bottom class to doppler preferences panel
  src/assets/scss/modules/_breadcrumb.scss
Labels: size/XS

#160 feat: padding correction in hero banner and breadcrumb
  src/assets/scss/modules/_breadcrumb.scss
  src/assets/scss/templates/_reportes.scss
Labels: size/S

#163 fix: add class for dropdown align in doppler old
  src/assets/scss/modules/_forms.scss
Labels: size/XS

#166 feat: add marks to slider
  src/assets/scss/templates/_doppler-plus.scss
  src/documentation/templates/buttons-component.html
  src/documentation/templates/plan-calculator.html
Labels: size/M

#167 fix: fix click in slider
  src/assets/scss/templates/_doppler-plus.scss
Labels: size/XS

#168 feat: add header in shopify page
  src/documentation/templates/integrations.html
Labels: size/S

#169 fix: fix in component form items
  src/assets/scss/modules/_forms.scss
  src/assets/scss/templates/_doppler-plus-plans-form.scss
Labels: size/XS

#171 fix: remove background grey on plancalculator
  src/assets/scss/templates/_doppler-plus.scss
Labels: size/S

#172 feat: change layout in Learn With Doppler carousel
  src/assets/scss/modules/_carousel.scss
Labels: size/XS
