Repository FromDoppler/doppler-style-guide, pull requests merged in 2022-03, with the labels that each got.

#27 fix: changing anchor elements by button for the editors menu
  src/assets/scss/modules/_dropdown.scss
  src/doc/templates/buttons-component.html
Labels: size/S

#29 fix: add support for buttons and links in menu editors
  src/assets/scss/modules/_dropdown.scss
  src/doc/templates/buttons-component.html
Labels: size/XS

#28 WIP: [DE-520] Agregado folder JS a la compilación con webpack
  package.json
  src/index.js
  src/util.js
  webpack-common.config.js
  webpack-prod.config.js
  webpack.config.js
  yarn.lock
Labels: size/L

#32 [DE-528] Publicar versiones de la documentación al CDN
  .env.production
  cdn-helpers/prepare.sh
  package.json
  src/documentation/templates/partials/_head.html
  webpack-common.config.js
  yarn.lock
Labels: size/S
