Repository FromDoppler/doppler-style-guide, pull requests merged in 2022-02, with the labels that each got.

#2 DE-457
  .env.development
  .env.production
  .gitignore
  .prettierignore
  package.json
  src/App.js
  src/index.js
  src/styles.scss
  src/util.js
  webpack.config.js
  yarn.lock
Labels: size/L

#3 build: run webpack build in CI/CD
  Dockerfile
Labels: size/XS

#4 feat: style implementation example
  src/styles.scss
Labels: size/S

#5 [DE-462] fixed manifest structure
  package.json
  webpack.config.js
Labels: size/S

#7 Add the property canonicalVersion to generated asset-manifest.json
  cdn-helpers/prepare.sh
Labels: size/S

#9 [DE-467] Configuración para assets
  webpack.config.js
Labels: size/S

#8 feat: add jquery as dependency
  package.json
  src/App.js
  src/index.js
  src/util.js
Labels: size/S

#15 [DE-480] Add legacy icon support
  src/assets/scss/libs/sassy-cast/_SassyCast.scss
  src/assets/scss/libs/webfont/template.css
  src/assets/scss/styles.scss
  src/index.scss
  src/webfont/compiled/index.css
Labels: size/XXL

#17 chore: removed deprecated mixins folder
  src/assets/scss/modules/_atomic-class.scss
  src/assets/scss/modules/_breakpoints.scss
  src/assets/scss/modules/_carousel.scss
  src/assets/scss/modules/_forms.scss
  src/assets/scss/modules/_index.scss
  src/assets/scss/modules/_language.scss
  src/assets/scss/modules/mixins/_alert.scss
  src/assets/scss/modules/mixins/_background-variant.scss
  src/assets/scss/modules/mixins/_badge.scss
  src/assets/scss/modules/mixins/_border-radius.scss
  src/assets/scss/modules/mixins/_box-shadow.scss
  src/assets/scss/modules/mixins/_buttons.scss
  src/assets/scss/modules/mixins/_caret.scss
  src/assets/scss/modules/mixins/_clearfix.scss
  src/assets/scss/modules/mixins/_color.scss
  src/assets/scss/modules/mixins/_float.scss
  src/assets/scss/modules/mixins/_forms.scss
  src/assets/scss/modules/mixins/_gradients.scss
  src/assets/scss/modules/mixins/_grid-framework.scss
  src/assets/scss/modules/mixins/_grid.scss
  src/assets/scss/modules/mixins/_hover.scss
  src/assets/scss/modules/mixins/_image.scss
  src/assets/scss/modules/mixins/_index.scss
  src/assets/scss/modules/mixins/_list-group.scss
  src/assets/scss/modules/mixins/_lists.scss
  src/assets/scss/modules/mixins/_nav-divider.scss
  src/assets/scss/modules/mixins/_pagination.scss
  src/assets/scss/modules/mixins/_reset-text.scss
  src/assets/scss/modules/mixins/_resize.scss
  src/assets/scss/modules/mixins/_ribbon.scss
  src/assets/scss/modules/mixins/_screen-reader.scss
  src/assets/scss/modules/mixins/_size.scss
  src/assets/scss/modules/mixins/_table-row.scss
  src/assets/scss/modules/mixins/_text-emphasis.scss
  src/assets/scss/modules/mixins/_text-hide.scss
  src/assets/scss/modules/mixins/_text-truncate.scss
  src/assets/scss/modules/mixins/_transition.scss
  src/assets/scss/modules/mixins/_visibility.scss
  src/assets/scss/styles.scss
  src/assets/scss/templates/_signup.scss
Labels: size/XXL

#21 [DE-484] agregado templates desde DopplerUI
  package.json
  src/doc/templates/_index.html
  src/doc/templates/accordion-component.html
  src/doc/templates/account-message-component.html
  src/doc/templates/animations-component.html
  src/doc/templates/big-data-input.html
  src/doc/templates/big-query.html
  src/doc/templates/breadcrumb-component.html
  src/doc/templates/buttons-component.html
  src/doc/templates/cards-component.html
  src/doc/templates/carousel-component.html
  src/doc/templates/checkout-success.html
  src/doc/templates/colors-component.html
  src/doc/templates/component-elements-checked.html
  src/doc/templates/confirmation-page.html
  src/doc/templates/contact-policy.html
  src/doc/templates/dashboard.html
  src/doc/templates/doppler-plus-plans-form.html
  src/doc/templates/doppler-plus.html
  src/doc/templates/footer-component.html
  src/doc/templates/forgot-password.html
  src/doc/templates/form_exclusive_features.html
  src/doc/templates/grid-system-component.html
  src/doc/templates/header-component.html
  src/doc/templates/hero-banner-component.html
  src/doc/templates/index.html
  src/doc/templates/integrations.html
  src/doc/templates/list-selection-page.html
  src/doc/templates/login.html
  src/doc/templates/messages-component.html
  src/doc/templates/modal-component.html
  src/doc/templates/nav-user-component.html
  src/doc/templates/partials/_breadcrumb.html
  src/doc/templates/partials/_footer.html
  src/doc/templates/partials/_head.html
  src/doc/templates/partials/_header.html
  src/doc/templates/partials/_msj-component.html
  src/doc/templates/partials/_nav.html
  src/doc/templates/partials/_navigation.html
  src/doc/templates/partials/_table-component.html
  src/doc/templates/partials/_tooltip-component.html
  src/doc/templates/payment-process.html
  src/doc/templates/plan-calculator.html
  src/doc/templates/preload-component.html
  src/doc/templates/promotional-page.html
  src/doc/templates/reports.html
  src/doc/templates/signup.html
  src/doc/templates/subscriber-history.html
  src/doc/templates/table-component.html
  src/doc/templates/tabs-component.html
  src/doc/templates/themes.html
  src/doc/templates/tooltip-component.html
  webpack.config.js
  yarn.lock
Labels: size/XXL
