Repository FromDoppler/doppler-style-guide, pull requests merged in 2022-08, with the labels that each got.

#110 [DE-709] Implementación de storybook
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/stories/Button.js
  src/stories/Button.stories.js
  src/stories/Header.js
  src/stories/Header.stories.js
  src/stories/Introduction.stories.mdx
  src/stories/Page.js
  src/stories/Page.stories.js
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  yarn.lock
Labels: size/XL

#111 fix: deprecation using / for division outside of calc
  src/assets/scss/modules/_grid-system.scss
Labels: size/XS

#118 chore(build): do not execute gitlint for INT branch
  Jenkinsfile
Labels: size/XS

#117 [DE-709] storybook ci configuration
  .storybook/preview-body.html
  .storybook/preview-head.html
  src/stories/Button.js
  src/stories/Button.stories.js
  src/stories/Header.js
  src/stories/Header.stories.js
  src/stories/Page.js
  src/stories/Page.stories.js
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  webpack.config.js
Labels: size/L

#119 [DE-709] Update dev script
  package.json
  yarn.lock
Labels: size/XS

#125 Renovate config
  renovate.json
Labels: size/M

#133 fix: add max width in component tooltip block
  src/assets/scss/modules/_tooltip.scss
Labels: size/XS

#138 Move some dependencies from devDependencies to dependencies
  package.json
Labels: size/M

#137 fix: support "show after load" mechanism without dp-library container
  src/assets/scss/helpers/_classes.scss
Labels: size/S
