Repository FromDoppler/doppler-style-guide, pull requests merged in 2022-09, with the labels that each got.

#148 DE-777 fix menu mfe
  src/assets/scss/templates/_doppler-plus.scss
  src/assets/scss/templates/_header.scss
Labels: size/XS

#150 Fix signup confirmation
  src/assets/scss/modules/_atomic-class.scss
  src/assets/scss/modules/_backgrounds.scss
  src/assets/scss/templates/_confirmation.scss
  src/documentation/templates/confirmation-page.html
Labels: size/M

#151 fix: remove unnecessary element and style
  src/assets/scss/templates/_confirmation.scss
  src/documentation/templates/confirmation-page.html
Labels: size/M

#152 feat: change gray and arrow headers to white background
  src/assets/scss/templates/_reportes.scss
Labels: size/S

#154 [DE-793] fix: broken sub menu
  src/assets/scss/templates/_header.scss
Labels: size/XS

#155 DE-796 - granuralize behavior initialization
  .storybook/preview-head.html
  src/documentation/templates/partials/_head.html
  src/index.js
  src/js/index.js
Labels: size/L
