Repository FromDoppler/doppler-style-guide, pull requests merged in 2023-04, with the labels that each got.

#253 feat: add zigzag to the end of purchase summary section
  src/assets/scss/templates/_payment-process.scss
  src/documentation/templates/payment-process.html
Labels: size/M

#260 Dat 1428 changes styles in purchase summary section
  src/assets/scss/templates/_payment-process.scss
  src/documentation/templates/payment-process.html
Labels: size/S

#262 feat: create storybook template for user account header and messages
  src/assets/scss/core/_typography.scss
  src/assets/scss/helpers/_colors.scss
  src/assets/scss/templates/_header.scss
  src/assets/scss/templates/_messages-header.scss
  src/documentation/templates/header-component.html
  src/stories/Header.js
  src/stories/Header.stories.js
Labels: size/L

#263 fix: change color button excel in doppler
  src/assets/scss/helpers/_classes.scss
Labels: size/XS

#264 fix: align content in campaigns scheduled
  src/assets/scss/helpers/_classes.scss
Labels: size/S

#267 feat: add new classes for each link
  .prettierignore
  src/assets/img/User.svg
  src/assets/img/bell-notification.svg
  src/assets/img/help.svg
  src/assets/scss/templates/_header.scss
  src/documentation/templates/header-component.html
  src/stories/Header.js
  src/stories/Header.stories.js
Labels: size/L

#271 fix: do not init UserMenu behavior by default
  .storybook/preview-head.html
  src/documentation/templates/partials/_head.html
  src/index.js
  src/js/index.js
Labels: size/S

#273 fix: remove space
  src/assets/scss/templates/_header.scss
Labels: size/XS

#275 fix: in menu responsive
  src/assets/img/Triangle.svg
  src/assets/scss/templates/_header.scss
  src/documentation/templates/header-component.html
  src/stories/Header.js
Labels: size/M
