Repository FromDoppler/doppler-style-guide, pull requests merged in 2023-06, with the labels that each got.

#308 fix: remove borders in menu
  src/assets/scss/templates/_header.scss
  src/stories/Header.js
Labels: size/S

#309 fix: add border bottom
  src/assets/scss/templates/_header.scss
Labels: size/XS

#310 DOP-1366 - Fix custom media gallery layout
  src/assets/scss/helpers/_classes.scss
Labels: size/L

#314 feat: add overlay to input file component - download and delete buttons
  src/assets/img/Delete.svg
  src/assets/img/Downloading.svg
  src/assets/img/picture_as_pdf.svg
  src/assets/scss/modules/_inputs.scss
  src/documentation/templates/component-inputs.html
Labels: size/L

#325 fix: add validation input password
  src/assets/scss/modules/_inputs.scss
  src/documentation/templates/component-inputs.html
  src/stories/Inputs.password.js
Labels: size/S

#322 feat: add input search component
  src/assets/img/search-icon.svg
  src/assets/scss/modules/_inputs.scss
  src/documentation/templates/component-inputs.html
  src/stories/Inputs.search.js
  src/stories/Inputs.search.stories.js
Labels: size/L

#329 fix: show eyed icon
  src/assets/scss/modules/_inputs.scss
Labels: size/XS

#337 Dat 1565 gallery messages for user in unlayer
  src/assets/scss/modules/_messages.scss
  src/documentation/templates/messages-component.html
Labels: size/L

#338 fix: add padding left for tel
  src/assets/scss/modules/_inputs.scss
  src/documentation/templates/component-inputs.html
  src/stories/Inputs.phone.js
Labels: size/M

#340 Gallery modals UI
  src/assets/scss/helpers/_colors.scss
  src/assets/scss/modules/_buttons.scss
  src/assets/scss/modules/_modal.scss
Labels: size/S

#342 Add new modal mod for error messages
  src/assets/scss/modules/_modal.scss
Labels: size/S

#341 fix: improve image gallery checkbox
  src/assets/scss/helpers/_classes.scss
Labels: size/S
