Repository FromDoppler/doppler-style-guide, pull requests merged in 2023-05, with the labels that each got.

#278 Dat 1475 add new invoice recipients in billing information
  src/assets/scss/templates/_payment-process.scss
  src/documentation/templates/payment-process.html
Labels: size/L

#284 feat: add save indicator
  src/assets/img/Saved.svg
  src/assets/img/Saving.svg
  src/assets/scss/core/_typography.scss
  src/assets/scss/helpers/_classes.scss
  src/stories/saved.indicator.js
  src/stories/saved.indicator.stories.js
Labels: size/L

#288 Add configuration to load Proxima Nova font
  .storybook/preview-head.html
  src/documentation/templates/partials/_head.html
  src/index.js
  src/js/index.js
  src/js/initFonts.js
  src/stories/Header.js
Labels: size/S

#285 feat: add container to save button
  src/assets/scss/templates/_payment-process.scss
  src/documentation/templates/payment-process.html
Labels: size/XXL

#289 feat: create buttons undo redo
  src/assets/img/btn-redo.svg
  src/assets/img/btn-undo.svg
  src/assets/scss/helpers/_classes.scss
  src/stories/Undo.Redo.js
  src/stories/Undo.Redo.stories.js
Labels: size/L

#290 fix: remove paddings and margins
  src/assets/scss/helpers/_classes.scss
Labels: size/M

#293 feat: create new submenu
  src/assets/scss/templates/_header.scss
  src/documentation/templates/header-component.html
  src/js/index.js
Labels: size/L

#298 feat: create input file component
  src/assets/scss/modules/_inputs.scss
  src/documentation/templates/component-inputs.html
  src/stories/Inputs.file.js
  src/stories/Inputs.file.stories.js
Labels: size/L

#300 Add styles for Unlayer editor custom media gallery
  src/assets/scss/helpers/_classes.scss
  src/assets/scss/modules/_modal.scss
Labels: size/L

#303 fix: complete change of input file component for accessibility
  src/assets/scss/modules/_inputs.scss
  src/documentation/templates/component-inputs.html
  src/stories/Inputs.file.js
  src/stories/Inputs.file.stories.js
Labels: size/L
