Repository FromDoppler/doppler-style-guide, pull requests merged in 2023-02, with the labels that each got.

#219 fix: color link doppler tip
  src/assets/scss/helpers/_classes.scss
Labels: size/XS

#222 fix: change button to 100 in mobile
  src/assets/scss/modules/_forms.scss
Labels: size/S

#224 De 923 fix checkbox
  src/assets/img/error-form.svg
  src/assets/scss/core/_typography.scss
  src/assets/scss/helpers/_animations.scss
  src/assets/scss/helpers/_colors.scss
  src/assets/scss/modules/_forms.scss
  src/documentation/templates/component-elements-checked.html
  src/documentation/templates/partials/_head.html
  src/stories/Checkbox.js
  src/stories/Checkbox.stories.js
Labels: size/XL

#225 [DE-808] Add pulse animation
  src/assets/scss/helpers/_animations.scss
  src/stories/Animations.js
  src/stories/Animations.stories.js
Labels: size/M

#226 [DE-808] Using region role in saving animation
  src/assets/scss/helpers/_animations.scss
  src/stories/Animations.js
  src/stories/Animations.stories.js
Labels: size/M

#227 fix(deps): update dependency sass to v1.58.3 - babel-loader to v9.1.2…
  package.json
  yarn.lock
Labels: size/XS
