Repository FromDoppler/doppler-style-guide, pull requests merged in 2023-03, with the labels that each got.

#235 feat: input password component creation
  src/assets/img/accent-mark.svg
  src/assets/img/denied.svg
  src/assets/scss/core/_typography.scss
  src/assets/scss/modules/_inputs.scss
  src/documentation/templates/component-inputs.html
  src/stories/Inputs.password.js
  src/stories/Inputs.password.stories.js
Labels: size/L

#243 fix: change role for class
  src/assets/scss/modules/_inputs.scss
  src/documentation/templates/component-elements-checked.html
  src/stories/Checkbox.js
Labels: size/M

#250 Dat 1409 fix beamer tooltip
  src/assets/scss/core/_settings.scss
  src/assets/scss/modules/_tooltip.scss
  src/assets/scss/templates/_header.scss
Labels: size/S

#252 feat: change secure payment && buy buttons
  src/assets/scss/templates/_payment-process.scss
  src/documentation/templates/payment-process.html
Labels: size/M

#254 Revert "feat: change secure payment && buy buttons"
  src/assets/scss/templates/_payment-process.scss
  src/documentation/templates/payment-process.html
Labels: size/M
