Repository FromDoppler/doppler-style-guide, pull requests merged in 2024-11, with the labels that each got.

#598 Dph #128 bubble config component
  src/assets/img/desktop-mockup.svg
  src/assets/img/mobile-mockup.svg
  src/assets/scss/helpers/_colors.scss
  src/assets/scss/modules/_index.scss
  src/assets/scss/modules/_widget-bubble.scss
  src/stories/Widget.Bubble.js
  src/stories/Widget.Bubble.stories.js
Labels: size/L

#600 Dph #129 new input radio styles
  src/assets/scss/modules/_forms.scss
  src/stories/Widget.Form.Input.js
  src/stories/Widget.Form.Input.stories.js
Labels: size/L

#601 Dat 2156
  src/assets/scss/modules/_modal.scss
Labels: size/S

#605 [DOI-1728] Add missing styles for widget hover card
  src/assets/scss/modules/_widget-card.scss
Labels: size/S

#609 [DOI-1743] Modify widget hover styles
  src/assets/scss/modules/_widget-card.scss
Labels: size/XS
