Repository FromDoppler/doppler-style-guide, pull requests merged in 2024-12, with the labels that each got.

#610 Dph #138 label with tooltip
  src/assets/scss/modules/_inputs.scss
  src/assets/scss/modules/_tooltip.scss
Labels: size/S

#619 Dph #178 delete widget modal
  src/assets/scss/modules/_modal.scss
  src/assets/scss/modules/_widget-card.scss
  src/stories/Widget.Info.Card.js
Labels: size/M

#621 feat: add right arrow next to "select" text
  src/assets/img/right-long-solid.svg
  src/assets/scss/helpers/_icons-glyph-smooth.scss
  src/assets/scss/modules/_widget-card.scss
  src/stories/Widget.Card.js
Labels: size/M

#623 Doi 1774 aclarar borde input search
  src/assets/scss/modules/_inputs.scss
Labels: size/XS

#622 Dph #179 nothing to show screen
  src/assets/img/nothing-to-show.svg
  src/assets/scss/helpers/_classes.scss
Labels: size/S
