Repository FromDoppler/doppler-style-guide, pull requests merged in 2024-09, with the labels that each got.

#562 [DOI-1576] Promotional video modal
  src/assets/scss/modules/_modal.scss
  src/assets/scss/templates/_list-selection.scss
  src/documentation/templates/modal-component.html
  src/js/index.js
Labels: size/M

#561 Dph #62 table component
  src/assets/scss/modules/_tables.scss
  src/documentation/templates/onsite-dashboard.html
  src/documentation/templates/table-component.html
Labels: size/L

#564 Dph #70 line chart styles
  package.json
  src/assets/scss/helpers/_colors.scss
  src/assets/scss/modules/_charts.scss
  src/assets/scss/modules/_index.scss
  src/assets/scss/modules/_tables.scss
  src/documentation/templates/onsite-dashboard.html
  src/index.js
  src/js/charts.js
  yarn.lock
Labels: size/L

#566 Remove unused console
  src/js/charts.js
Labels: size/XS

#565 Dph #59 bar chart styles
  src/documentation/templates/onsite-dashboard.html
  src/index.js
  src/js/charts.js
Labels: size/M

#569 Dph #74 widgets cards styles
  src/assets/scss/modules/_index.scss
  src/assets/scss/modules/_ribbons.scss
  src/assets/scss/modules/_widget-card.scss
  src/stories/Widget.Card.js
  src/stories/Widget.Card.stories.js
Labels: size/L

#570 Dph #74 widgets cards styles
  src/assets/scss/modules/_widget-card.scss
  src/stories/Widget.Card.js
Labels: size/XS

#571 Dph #87 widget card info styles
  src/assets/scss/modules/_dropdown.scss
  src/assets/scss/modules/_tables.scss
  src/assets/scss/modules/_widget-card.scss
  src/stories/Widget.Card.js
  src/stories/Widget.Info.Card.js
  src/stories/Widget.Info.Card.stories.js
Labels: size/L

#573 Dph #92 fix widget card styles
  src/assets/scss/modules/_ribbons.scss
Labels: size/XS
