Repository FromDoppler/doppler-style-guide, pull requests merged in 2025-02, with the labels that each got.

#638 [DOI-1895] Add new component "widget plan progress bar"
  src/assets/scss/modules/_widget-card.scss
  src/stories/Widget.Plan.Progress.js
  src/stories/Widget.Plan.Progress.stories.js
Labels: size/M

#639 Color rojo para la barra de progreso
  src/assets/scss/modules/_widget-card.scss
Labels: size/XS

#640 chore: add margin and bottom
  src/stories/Widget.Plan.Progress.js
Labels: size/XS

#644 Classes for date input
  src/assets/scss/modules/_forms.scss
Labels: size/S

#652 [DAT-2280]
  src/assets/scss/modules/_modal.scss
Labels: size/S
